version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react-app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs
    depends_on:
      - backend
  backend:
    build: .
    image: node-app
    ports:
      - '5000:5000'